### ISSUE TITLE
Syntax highlighting not the same as HTML gitbook

### ISSUE THREAD

**Issue by paulkoegel** [paulkoegel/redux-offline-docs#4]
Cannot use @gaearon's version of the `prism` syntax highlighter. See this issue:
https://github.com/gaearon/gitbook-plugin-prism/issues/4

currently disabling prism in redux's `book.json` before converting to offline docs. syntax highlighting works, but is not as good as for the HTML gitbook.
This needs to be fixed in the prism repo, but creating an issue here as well for documentation and in case people wonder about the different code colours :)

**Comment by gaearon** [comment]
I wonder if https://github.com/gaearon/gitbook-plugin-prism/pull/3 helps here?

**Comment by paulkoegel** [comment]
fixed via https://github.com/rackt/redux/commit/a5d985f5a02d887d9ba285dbba2446f0d126c823
and as of https://github.com/paulkogel/redux-offline-docs/commit/dfc7bc0404eba61366f146356083fa9eeaf7f5da we have the "prism" style highlighting in the offline docs as well :)
