### ISSUE TITLE
cannot create document

### ISSUE THREAD

**Issue by lesar** [paulkoegel/redux-offline-docs#7]
I try to build new epub but nothing work:  

- your bash sh script use ' unless " but this is easy to correct
- I try to use this link [React1](https://github.com/rackt/redux) but seam not be usefull

so I try this link [react2](https://github.com/reactjs/redux) instead but no ebook where created  
best regards

**Comment by paulkoegel** [comment]
Hi @lesar,

thanks for noting that `'` should be replaced with`"`" in my script. However, even then `$HOME` didn't get resolved for me. The script I actually used had the explicit folder path of my machine in it.

I've adjusted the README and uploaded new versions of the files, which you can just download.
Let me know whether the new instructions and script work for you.

**Comment by paulkoegel** [comment]
Does the problem persist for you, @lesar, or do you have any more feedback on this?

**Comment by paulkoegel** [comment]
Closing due lack of response. issue was fixed in 8ea37d0cab03d04c68da6e3919dd809d33068880 and ffe7991ef9ee138631e83f56ad6fe8d648a82c99.
